### ISSUE TITLE
Can't add toggle

### ISSUE THREAD

**Issue by iskandar1023** [jlhonora/multistatetogglebutton#36]
i'm sorry but i need help in implementing this, it's always crashing even in the basic test app. here is the mainactivity.java

    public class MainActivity extends AppCompatActivity {
    @Override
    protected void onCreate(Bundle savedInstanceState) {
        super.onCreate(savedInstanceState);
        setContentView(R.layout.activity_main);
        Toolbar toolbar = (Toolbar) findViewById(R.id.toolbar);
        setSupportActionBar(toolbar);

        FloatingActionButton fab = (FloatingActionButton) findViewById(R.id.fab);

        MultiStateToggleButton button = (MultiStateToggleButton) this.findViewById(R.id.toggle);

        CharSequence[] texts = new CharSequence[]{"tes1", "tes2"};
        button.setElements(texts);
    }
    }

activity_main.xml

    <?xml version="1.0" encoding="utf-8"?>
    <android.support.design.widget.CoordinatorLayout xmlns:android="http://schemas.android.com/apk/res/android"
    xmlns:app="http://schemas.android.com/apk/res-auto"
    xmlns:tools="http://schemas.android.com/tools"
    android:layout_width="match_parent"
    android:layout_height="match_parent"
    android:fitsSystemWindows="true"
    tools:context="com.iskandarivan.playground.MainActivity">

    <android.support.design.widget.AppBarLayout
        android:layout_width="match_parent"
        android:layout_height="wrap_content"
        android:theme="@style/AppTheme.AppBarOverlay">

        <android.support.v7.widget.Toolbar
            android:id="@+id/toolbar"
            android:layout_width="match_parent"
            android:layout_height="?attr/actionBarSize"
            android:background="?attr/colorPrimary"
            app:popupTheme="@style/AppTheme.PopupOverlay" />

    </android.support.design.widget.AppBarLayout>

    <include layout="@layout/content_main" />

    <org.honorato.multistatetogglebutton.MultiStateToggleButton
        android:id="@+id/toggle"
        android:layout_width="wrap_content"
        android:layout_height="wrap_content"
        android:layout_marginTop="10dip"/>

    <android.support.design.widget.FloatingActionButton
        android:id="@+id/fab"
        android:layout_width="wrap_content"
        android:layout_height="wrap_content"
        android:layout_gravity="bottom|end"
        android:layout_margin="@dimen/fab_margin"
        android:src="@android:drawable/ic_dialog_email" />

    </android.support.design.widget.CoordinatorLayout>

logcat

06-19 13:20:05.905 24129-24129/com.iskandarivan.playground E/AndroidRuntime: FATAL EXCEPTION: main
                                                                             Process: com.iskandarivan.playground, PID: 24129
                                                                             java.lang.RuntimeException: Unable to start activity ComponentInfo{com.iskandarivan.playground/com.iskandarivan.playground.MainActivity}: android.view.InflateException: Binary XML file line #26: Binary XML file line #26: Error inflating class org.honorato.multistatetogglebutton.MultiStateToggleButton
                                                                                 at android.app.ActivityThread.performLaunchActivity(ActivityThread.java:2430)
                                                                                 at android.app.ActivityThread.handleLaunchActivity(ActivityThread.java:2490)
                                                                                 at android.app.ActivityThread.-wrap11(ActivityThread.java)
                                                                                 at android.app.ActivityThread$H.handleMessage(ActivityThread.java:1355)
                                                                                 at android.os.Handler.dispatchMessage(Handler.java:102)
                                                                                 at android.os.Looper.loop(Looper.java:148)
                                                                                 at android.app.ActivityThread.main(ActivityThread.java:5445)
                                                                                 at java.lang.reflect.Method.invoke(Native Method)
                                                                                 at com.android.internal.os.ZygoteInit$MethodAndArgsCaller.run(ZygoteInit.java:726)
                                                                                 at com.android.internal.os.ZygoteInit.main(ZygoteInit.java:616)
                                                                                 at de.robv.android.xposed.XposedBridge.main(XposedBridge.java:132)
                                                                              Caused by: android.view.InflateException: Binary XML file line #26: Binary XML file line #26: Error inflating class org.honorato.multistatetogglebutton.MultiStateToggleButton
                                                                                 at android.view.LayoutInflater.inflate(LayoutInflater.java:539)
                                                                                 at de.robv.android.xposed.XposedBridge.invokeOriginalMethodNative(Native Method)
                                                                                 at de.robv.android.xposed.XposedBridge.handleHookedMethod(XposedBridge.java:740)
                                                                                 at android.view.LayoutInflater.inflate(<Xposed>)
                                                                                 at android.view.LayoutInflater.inflate(LayoutInflater.java:423)
                                                                                 at android.view.LayoutInflater.inflate(LayoutInflater.java:374)
                                                                                 at android.support.v7.app.AppCompatDelegateImplV7.setContentView(AppCompatDelegateImplV7.java:280)
                                                                                 at android.support.v7.app.AppCompatActivity.setContentView(AppCompatActivity.java:140)
                                                                                 at com.iskandarivan.playground.MainActivity.onCreate(MainActivity.java:17)
                                                                                 at android.app.Activity.performCreate(Activity.java:6251)
                                                                                 at android.app.Instrumentation.callActivityOnCreate(Instrumentation.java:1107)
                                                                                 at android.app.ActivityThread.performLaunchActivity(ActivityThread.java:2383)
                                                                                 at android.app.ActivityThread.handleLaunchActivity(ActivityThread.java:2490) 
                                                                                 at android.app.ActivityThread.-wrap11(ActivityThread.java) 
                                                                                 at android.app.ActivityThread$H.handleMessage(ActivityThread.java:1355) 
                                                                                 at android.os.Handler.dispatchMessage(Handler.java:102) 
                                                                                 at android.os.Looper.loop(Looper.java:148) 
                                                                                 at android.app.ActivityThread.main(ActivityThread.java:5445) 
                                                                                 at java.lang.reflect.Method.invoke(Native Method) 
                                                                                 at com.android.internal.os.ZygoteInit$MethodAndArgsCaller.run(ZygoteInit.java:726) 
                                                                                 at com.android.internal.os.ZygoteInit.main(ZygoteInit.java:616) 
                                                                                 at de.robv.android.xposed.XposedBridge.main(XposedBridge.java:132) 
                                                                              Caused by: android.view.InflateException: Binary XML file line #26: Error inflating class org.honorato.multistatetogglebutton.MultiStateToggleButton
                                                                                 at android.view.LayoutInflater.createView(LayoutInflater.java:645)
                                                                                 at android.view.LayoutInflater.createViewFromTag(LayoutInflater.java:764)
                                                                                 at android.view.LayoutInflater.createViewFromTag(LayoutInflater.java:704)
                                                                                 at android.view.LayoutInflater.rInflate(LayoutInflater.java:835)
                                                                                 at android.view.LayoutInflater.rInflateChildren(LayoutInflater.java:798)
                                                                                 at android.view.LayoutInflater.inflate(LayoutInflater.java:515)
                                                                                 at de.robv.android.xposed.XposedBridge.invokeOriginalMethodNative(Native Method) 
                                                                                 at de.robv.android.xposed.XposedBridge.handleHookedMethod(XposedBridge.java:740) 
                                                                                 at android.view.LayoutInflater.inflate(<Xposed>) 
                                                                                 at android.view.LayoutInflater.inflate(LayoutInflater.java:423) 
                                                                                 at android.view.LayoutInflater.inflate(LayoutInflater.java:374) 
                                                                                 at android.support.v7.app.AppCompatDelegateImplV7.setContentView(AppCompatDelegateImplV7.java:280) 
                                                                                 at android.support.v7.app.AppCompatActivity.setContentView(AppCompatActivity.java:140) 
                                                                                 at com.iskandarivan.playground.MainActivity.onCreate(MainActivity.java:17) 
                                                                                 at android.app.Activity.performCreate(Activity.java:6251) 
                                                                                 at android.app.Instrumentation.callActivityOnCreate(Instrumentation.java:1107) 
                                                                                 at android.app.ActivityThread.performLaunchActivity(ActivityThread.java:2383) 
                                                                                 at android.app.ActivityThread.handleLaunchActivity(ActivityThread.java:2490) 
                                                                                 at android.app.ActivityThread.-wrap11(ActivityThread.java) 
                                                                                 at android.app.ActivityThread$H.handleMessage(ActivityThread.java:1355) 
                                                                                 at android.os.Handler.dispatchMessage(Handler.java:102) 
                                                                                 at android.os.Looper.loop(Looper.java:148) 
                                                                                 at android.app.ActivityThread.main(ActivityThread.java:5445) 
                                                                                 at java.lang.reflect.Method.invoke(Native Method) 
                                                                                 at com.android.internal.os.ZygoteInit$MethodAndArgsCaller.run(ZygoteInit.java:726) 
                                                                                 at com.android.internal.os.ZygoteInit.main(ZygoteInit.java:616) 
                                                                                 at de.robv.android.xposed.XposedBridge.main(XposedBridge.java:132) 
                                                                              Caused by: java.lang.reflect.InvocationTargetException
                                                                                 at java.lang.reflect.Constructor.newInstance(Native Method)
                                                                                 at android.view.LayoutInflater.createView(LayoutInflater.java:619)
                                                                                 at android.view.LayoutInflater.createViewFromTag(LayoutInflater.java:764) 
                                                                                 at android.view.LayoutInflater.createViewFromTag(LayoutInflater.java:704) 
                                                                                 at android.view.LayoutInflater.rInflate(LayoutInflater.java:835) 
                                                                                 at android.view.LayoutInflater.rInflateChildren(LayoutInflater.java:798) 
                                                                                 at android.view.LayoutInflater.inflate(LayoutInflater.java:515) 
                                                                                 at de.robv.android.xposed.XposedBridge.invokeOriginalMethodNative(Native Method) 
                                                                                 at de.robv.android.xposed.XposedBridge.handleHookedMethod(XposedBridge.java:740) 
                                                                                 at android.view.LayoutInflater.inflate(<Xposed>) 
                                                                                 at android.view.LayoutInflater.inflate(LayoutInflater.java:423) 
                                                                                 at android.view.LayoutInflater.inflate(LayoutInflater.java:374) 
                                                                                 at android.support.v7.app.AppCompatDelegateImplV7.setContentView(AppCompatDelegateImplV7.java:280) 
                                                                                 at android.support.v7.app.AppCompatActivity.setContentView(AppCompatActivity.java:140) 
                                                                                 at com.iskandarivan.playground.MainActivity.onCreate(MainActivity.java:17) 
                                                                                 at android.app.Activity.performCreate(Activity.java:6251) 
                                                                                 at android.app.Instrumentation.callActivityOnCreate(Instrumentation.java:1107) 
                                                                                 at android.app.ActivityThread.performLaunchActivity(ActivityThread.java:2383) 
                                                                                 at android.app.ActivityThread.handleLaunchActivity(ActivityThread.java:2490) 
                                                                                 at android.app.ActivityThread.-wrap11(ActivityThread.java) 
                                                                                 at android.app.ActivityThread$H.handleMessage(ActivityThread.java:1355) 
                                                                                 at android.os.Handler.dispatchMessage(Handler.java:102) 
                                                                                 at android.os.Looper.loop(Looper.java:148) 
                                                                                 at android.app.ActivityThread.main(ActivityThread.java:5445) 
                                                                                 at java.lang.reflect.Method.invoke(Native Method) 
                                                                                 at com.android.internal.os.ZygoteInit$MethodAndArgsCaller.run(ZygoteInit.java:726) 
                                                                                 at com.android.internal.os.ZygoteInit.main(ZygoteInit.java:616) 
                                                                                 at de.robv.android.xposed.XposedBridge.main(XposedBridge.java:132) 
                                                                              Caused by: java.lang.NullPointerException: Attempt to get length of null array
                                                                                 at org.honorato.multistatetogglebutton.MultiStateToggleButton.<init>(MultiStateToggleButton.java:41)
                                                                                 at java.lang.reflect.Constructor.newInstance(Native Method) 
                                                                                 at android.view.LayoutInflater.createView(LayoutInflater.java:619) 
                                                                                 at android.view.LayoutInflater.createViewFromTag(LayoutInflater.java:764) 
                                                                                 at android.view.LayoutInflater.createViewFromTag(LayoutInflater.java:704) 
                                                                                 at android.view.LayoutInflater.rInflate(LayoutInflater.java:835) 
                                                                                 at android.view.LayoutInflater.rInflateChildren(LayoutInflater.java:798) 
                                                                                 at android.view.LayoutInflater.inflate(LayoutInflater.java:515) 
                                                                                 at de.robv.android.xposed.XposedBridge.invokeOriginalMethodNative(Native Method) 
                                                                                 at de.robv.android.xposed.XposedBridge.handleHookedMethod(XposedBridge.java:740) 
                                                                                 at android.view.LayoutInflater.inflate(<Xposed>) 
                                                                                 at android.view.LayoutInflater.inflate(LayoutInflater.java:423) 
                                                                                 at android.view.LayoutInflater.inflate(LayoutInflater.java:374) 
                                                                                 at android.support.v7.app.AppCompatDelegateImplV7.setContentView(AppCompatDelegateImplV7.java:280) 
                                                                                 at android.support.v7.app.AppCompatActivity.setContentView(AppCompatActivity.java:140) 
                                                                                 at com.iskandarivan.playground.MainActivity.onCreate(MainActivity.java:17) 
                                                                                 at android.app.Activity.performCreate(Activity.java:6251) 
                                                                                 at android.app.Instrumentation.callActivityOnCreate(Instrumentation.java:1107) 
                                                                                 at android.app.ActivityThread.performLaunchActivity(ActivityThread.java:2383) 
                                                                                 at android.app.ActivityThread.handleLaunchActivity(ActivityThread.java:2490) 
                                                                                 at android.app.ActivityThread.-wrap11(ActivityThread.java) 
                                                                                 at android.app.ActivityThread$H.handleMessage(ActivityThread.java:1355) 
                                                                                 at android.os.Handler.dispatchMessage(Handler.java:102) 
                                                                                 at android.os.Looper.loop(Looper.java:148) 
                                                                                 at android.app.ActivityThread.main(ActivityThread.java:5445) 
                                                                                 at java.lang.reflect.Method.invoke(Native Method) 
                                                                                 at com.android.internal.os.ZygoteInit$MethodAndArgsCaller.run(ZygoteInit.java:726) 
                                                                                 at com.android.internal.os.ZygoteInit.main(ZygoteInit.java:616) 
                                                                                 at de.robv.android.xposed.XposedBridge.main(XposedBridge.java:132) 

Actually i wan't to add it to a fragment, but adding it to an activity doesn't help too. Please tell me if i made a mistake in implementing it. Any help would be appreciated, thank you!

**Comment by jlhonora** [comment]
Hi Ivan,

Do you have some sample code you can share?

**Comment by NicoChacha** [comment]
Hi, 
I had the same issue. I think the cause is about the xml attribute "value". It seems to be mandatory on the xml file. If you look the view's constructor, the setElements(...) method with an array null throws a NullPointerException.
Hope this will help you to fix this issue.

**Comment by jlhonora** [comment]
Great catch, fixed in 0.2.2

**Comment by NicoChacha** [comment]
So fast :D

**Comment by iskandar1023** [comment]
Ah well, thank you very much...i'm trying it now

**Comment by iskandar1023** [comment]
Thank you so much, it's working now!
Now i'm waiting for the implementation of shadow, although i know a dirty workaround for it :+1:

**Comment by Murali-Krishnan** [comment]
Hi @jlhonora ,
I am using the latest version (0.2.2), but still facing the same issue
Binary XML file line #62: Error inflating class org.honorato.multistatetogglebutton.MultiStateToggleButton
            implementation 'org.honorato.multistatetogglebutton:multistatetogglebutton:0.2.2'

As pre NicoChacha statement, I have set values in XML as well as in java class too.
            mstb:values="@array/wordsArray" //XML Code
            mstb_multi_id.setElements(R.array.wordsArray, 0) // Java Code
